stages:
  - building
  - testing
  - deploying

1-monitor-deploy-production:
  stage: deploying
  script:
    - eval $(ssh-agent -s)
    - echo "$MONITOR_TOKEN" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan "$HOST" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git remote add production "$USER"@"$HOST":/var/www/monitor-pipe.git
    - git remote -v
    - git status
    - git push -f production HEAD:master
  when: manual
